### ISSUE TITLE
XCSkip equivalents in swift-testing

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-testing#120]
### Description

The old XCTest based test case:
```swift
func testDemo() throws {
    let value: Int? = ...
    guard let value else {
        throw XCTSkip("Some skip message here")

    }
    XCTAssertEqual(value, 3)
}
```

The closest migrating to swift-testing I could think of. 
```swift
func testDemo() throws {
    let value: Int? = ...
    guard let value else {
        withKnownIssue {
            throw "Some skip message here"
        }
        return
    }
    #expect(BloomFilter(type: type).value == expectedValue)
}
extension String: Error {}
```

### Expected behavior

`XCSkip` have an equivalent in swift-testing

### Actual behavior

`XCSkip` have no equivalent in swift-testing

**Comment by grynspan** [comment]
Use the `.enabled(if:)`, `.disabled(if:)`, and `.disabled()` traits to control if a test will run. See: https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing/enablinganddisabling

**Comment by grynspan** [comment]
See also: https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing/migratingfromxctest#Converting-XCTSkip-XCTSkipIf-and-XCTSkipUnless-calls

**Comment by grynspan** [comment]
![Image](https://github.com/user-attachments/assets/fa59e131-a4f1-467b-9655-2da4a52f3769)

**Comment by grynspan** [comment]
Tracked internally as rdar://159150449.
