### ISSUE TITLE
Update Getting Started docs to use Swift main branch features

### ISSUE THREAD

**Issue by grynspan** [apple/swift-testing#126]
We now have functional support for swift-testing in Swift Package Manager (as of https://github.com/apple/swift-package-manager/pull/7047). We should update our documentation:

- Point developers to the main branch instead of 5.10 again;
- Show developers how to invoke `swift test` in a way that triggers swift-testing; and
- Show developers how to use `XCTestScaffold` _only_ when using an older toolchain (with the appropriate caveats and nuances emphasized.)

**Comment by Kyle-Ye** [comment]
Do we have any plan to cherry-pick the related integrating PRs from main back to release/5.10?

**Comment by grynspan** [comment]
No, Swift 5.10 will not include support for swift-testing.

**Comment by Kyle-Ye** [comment]
> No, Swift 5.10 will not include support for swift-testing.

Got it. Thanks
