### ISSUE TITLE
Provide an API to supply explicit file/line locations

### ISSUE THREAD

**Issue by allevato** [apple/swift-testing#15]
### Description

When writing helper functions that call XCTest assertion methods, it's common to have those helpers take defaulted `file`/`line` arguments and pass those through to the XCT* calls; this makes the failure message appear at the call site of the helper method instead of all being grouped inside helper. A contrived example:

```swift
func assertIsNotEmpty(_ collection: some Collection, file: StaticString = #file, line: UInt = #line) {
  XCTAssertFalse(collection.isEmpty, file: file, line: line)
}

func testSomething() {
  assertIsNotEmpty([])  // failure appears here
}
```

I didn't see this explicitly supported by the APIs currently available; I looked in the vision doc for future plans but just found [this reference](https://github.com/apple/swift-testing/blob/main/Documentation/Vision.md#expectations):

> The source code location of the expectation, typically using the format #file:#line:#column. This helps test authors jump quickly to the line of code to view context, and lets IDEs present the failure in their UI at that location.

Maybe adding defaulted `file` and `line` arguments to the `#expect`/`#require` macros would be sufficient here?

### swift-testing version/commit hash

0.0.0-initial

**Comment by grynspan** [comment]
We would probably expose this as an explicit `sourceLocation` argument, since there's several more fields you'd need to populate, not just `file` and `line`.

We were already tracking this internally as rdar://112974442 but I hadn't had a chance to migrate it to GitHub yet. Thanks for filing! We'll track with this issue going forward.
