### ISSUE TITLE
Support for expected "crashers"

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-testing#157]
### Description

It should be possible to test that some code triggers process termination with a nonzero exit code and optionally certain output to standard output and error.

**Comment by grynspan** [comment]
Tracked internally as rdar://111625303.

**Comment by ed-irl** [comment]
Is there an issue one can subscribe to, in order to track the completion & release of this feature (it's not in the current release AFAICT)?

**Comment by grynspan** [comment]
The draft pitch is here: #324

If/when that gets merged, the feature's been approved.
