### ISSUE TITLE
Provide fixme Infrastructure  support for IDE

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-testing#197]
### Description

Provide fixme/solution metadata so that Swift IDE can use it to display GUI fix tip.

example: Apple's Xcode IDE support for swift-docc's fixme infra.
https://github.com/apple/swift-docc/blob/9cbc55d7496b0c1a1b67e883341b57122d8d1b33/Sources/SwiftDocC/Checker/Checkers/SeeAlsoInTopicsHeadingChecker.swift#L20-L40

https://github.com/apple/swift-docc/pull/8

https://github.com/apple/swift-docc/blob/main/Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterTests.swift

<img width="1224" alt="image" src="https://github.com/apple/swift-testing/assets/43724855/b0e61b20-69d8-481f-b66c-4dab6554d095">

PS: I'm not asking for a specific IDE support here. I'm requesting a feature of swift-testing to emit fixme metadata so that the IDE team(Xcode, VSCode or other IDE) may use it later.

### Usage

1. Simple usage

Provide a quick fixme to update the `#expect` expression.

eg.
```swift
let a = test() // returns false here
#expect(a == true) // emit a fixme of "Change to a == false"
```

2. Complex usage

```swift
func test(value: UInt32) -> UInt32 {
	// some complex magic bitwise code
}

func merge(_ t1: UInt32, _ t2: UInt32) -> UInt32 {
	// some complex magic bitwise code
}

@Test(arguments: [
    (0x0000_0000, 0x0000_0000, 0x0000_0000),
    (0xFFFF_FFFF, 0x0000_0000, 0x17F8_3A02),
    (0xFFFF_FFFF, 0xFFFF_FFFF, 0x3258_2C16),
    (0xAABB_CCDD, 0x0000_0000, 0xAABB_CCDD),
])
func merge(_ a: UInt32, _ b: UInt32, _ c: UInt32) {
    let t1 = test(value: a)
    let t2 = test(value: b)
    #expect(merge(t1, t2) == c)
}
```

The above code will pass the tests here. But when writing the test case, we do not know the expected `c` value in advance. So we'll write the following code to make it fail on purpose.

```swift
@Test(arguments: [
    (0x0000_0000, 0x0000_0000, 0x0000_0000),
    (0xFFFF_FFFF, 0x0000_0000, 0x0000_0000),
    (0xFFFF_FFFF, 0xFFFF_FFFF, 0x0000_0000),
    (0xAABB_CCDD, 0x0000_0000, 0x0000_0000),
])
```

After it fails, we'll check the test output and update the failing `c` value manually. I think it will be great if we can just emit fixme so that after IDE adapts it, we can just click to update the c value here.

### Expected behavior

```swift
@Test(arguments: [
    (0x0000_0000, 0x0000_0000, 0x0000_0000),
    (0xFFFF_FFFF, 0x0000_0000, 0x0000_0000), // Emit fixme to "Change to 0x17F8_3A02"
    (0xFFFF_FFFF, 0xFFFF_FFFF, 0x0000_0000), // Emit fixme to "Change to 0x3258_2C16"
    (0xAABB_CCDD, 0x0000_0000, 0x0000_0000), // Emit fixme to "Change to 0xAABB_CCDD"
])
```

### Actual behavior

None

**Comment by Kyle-Ye** [comment]
> It is not a goal of the testing library to try to correct issues with tests as it is, generally speaking, not possible to know what the "correct" state is. For example, using your first example FIXME:
> 
> ```swift
> let a = test() // returns false here
> #expect(a == true) // emit a fixme of "Change to a == false"
> ```
> 
> Is the correct fix to change the expectation, or to fix the code being tested? There's no real way for the testing library to know what the _correct_ fix is here, so offering a fixme to simply silence a test failure would invite developers to silently break their tests. That would not be ideal!

I agree we should not enable it by default because it does more harm here when test case fails.

However I still think it is valuable to provide some API which will emit fixme for the right value instead of copy paste it manually.


For a more concrete example of the usage 2 I provide above: 

https://github.com/apple/swift-markdown/blob/6f5d869207b3584465786e26581c2d298ae4d7ce/Tests/MarkdownTests/Parsing/BlockDirectiveParserTests.swift#L1058-L1067

When writing case test for this [PR](https://github.com/apple/swift-markdown/pull/154), I do not know the expect compared value here. So I just use a random string(or empty string) and run the test case. After it fails, I check the console and copy paste the left value to the code as the "expect" right value.

The old workflow
```swift
// Step 1: Write the test case with an empty string as expected value
let expected = ""
XCTAssertEqual(document.debugDescription(options: .printSourceLocations), expected)

// Step 2: Run it and fails.
// console: "" is not equal to "xxx"

// Step 3: Copy the diff value from the test result in the console as the new expected value
let expected = #"""
xxx
"""#
XCTAssertEqual(document.debugDescription(options: .printSourceLocations), expected)
```

I'm expecting getting a workflow like this in swift-testing:

```swift
// Step 1: Write the test case
#expectedWithFixit(document.debugDescription(options: .printSourceLocations), "")

// Step 2: Run it and emit a GUI fixit if the target IDE supports it
#expectedWithFixit(document.debugDescription(options: .printSourceLocations), "") // Fixit: update "" to "xx"

// Step 3: Click it and done. IDE will do the replacement.
#expect(document.debugDescription(options: .printSourceLocations), "xx")
```

**Comment by grynspan** [comment]
There are certainly some interesting possibilities here, but as far as I can see they fall on the IDE to implement. If you're interested in having Xcode add functionality like this, I'd recommend filing feedback with Apple at https://feedback.apple.com.

**Comment by Kyle-Ye** [comment]
> There are certainly some interesting possibilities here, but as far as I can see they fall on the IDE to implement. If you're interested in having Xcode add functionality like this, I'd recommend filing feedback with Apple at [feedback.apple.com](https://feedback.apple.com).

Nope. This is not IDE specific and such implementation code is on library side.

> PS: I'm not asking for a specific IDE support here. I'm requesting a feature of swift-testing to emit fixme metadata so that the IDE team(Xcode, VSCode or other IDE) may use it later.

If swift-testing decided to add such macro to emit corresponding fixit metadata the same as swift-docc, any IDE can achieve the fixit effect described here in theory (although currently maybe Xcode IDE will be the only potential consumer here)

Anyway, I got your standpoint here.
