### ISSUE TITLE
Getting started link does not work

### ISSUE THREAD

**Issue by shurale85** [apple/swift-testing#212]
### Description

Getting started link https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing/temporarygettingstarted does not work

**Comment by grynspan** [comment]
Note: SPI now needs to re-add swift-testing, so this change will need a bit of time to percolate. Thanks for reporting!

**Comment by grynspan** [comment]
Resolution on SPI side tracked by:

https://github.com/SwiftPackageIndex/PackageList/pull/6347
https://github.com/SwiftPackageIndex/PackageList/pull/6348

Things should be working now.
