### ISSUE TITLE
Include file and line number for failed/erroring tests in xUnit file

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-testing#253]
### Description

I'm currently using the xUnit output from swift-testing to update test results in the VSCode Swift extension. I was wondering would it be possible to add additional data to the file when a test fails. Currently we get the failure message but we don't get any information about where the failure is. Currently the output is
```
<testcase classname="test.Thing" name="testThis()" time="0.001592814">
  <failure message="Expectation failed: 2+2 == 5" />
</testcase>
```
Would it be possible to add location details to the failure eg
```
<testcase classname="test.Thing" name="testThis()" time="0.001592814">
  <failure message="Expectation failed: 2+2 == 5" filename="Sources/Test/Test.swift" line="45" />
</testcase>
```

**Comment by grynspan** [comment]
swift-testing's xUnit output is intended to have parity with what XCTest currently produces, and XCTest does not (at least as far as I'm aware) include source location information for tests or events.

If this information is produced by XCTest-based tests but not by swift-testing-based tests, please reopen.
