### ISSUE TITLE
In-code parallelizable annotation

### ISSUE THREAD

**Issue by pepicrft** [apple/swift-testing#315]
### Description

At [Tuist](https://github.com/tuist/tuist), we use Xcode projects to model the project. We have a test suite of acceptance tests, some of which are not parallelizable because they use system resources that are not exceptionally designed for parallelization, like the management of simulators via `simctl.`
We've considered using schemes to group parallelizable tests, but managing those becomes tedious and error-prone. Since a new test framework is in the making, we wondered if it'd be an excellent opportunity to introduce some annotation at the test class level where developers can annotate which tests are parallelizable. Elixir does it and I think it's an amazing ergonomic that `swift-testing` could adopt through function annotations:

```ex
defmodule MyTests do
    use ExUnit.Case, async: true

    test "it adds" do
      # ...
    end
end
```
There's some [literature here](https://dockyard.com/blog/2019/02/13/understanding-test-concurrency-in-elixir) around how it works in Elixir, but the LT;DR; version of it is that they run the parallel tests first, and then the rest sequentially.

**Comment by grynspan** [comment]
Tests in swift-testing are parallelized by default (when using a main-branch Swift toolchain, at least.) Parallelization is opt-_out_ using actor isolation or the experimental `.serial` trait.

With that information in mind, what use cases do you see for a trait like this?

**Comment by pepicrft** [comment]
> With that information in mind, what use cases do you see for a trait like this?

I think the `.serial` trait is what I was looking for. We'd use it to mark as serial tests that we can't parallelize for whatever reason (e.g., acceptance tests that depend on some global state within the Swift runtime or in the system).
