### ISSUE TITLE
Define and implement a stable JSON schema for output.

### ISSUE THREAD

**Issue by plemarquand** [apple/swift-testing#368]
### Description

Experimental event streaming support was added in #286. Issues are reported as individual events with richly structured JSON that describe the failure. This is great for tools that need to work with and transform raw issues, but many tools will just want to use the human readable failure string, i.e: `Expectation failed: 1 == 2`. 

Swift-testing has done a lot of work to build up a nice message, and it would be nice to avoid reimplementing this in other tools (and keeping it up to date).

Feature: Add a new `message` field to the `issueRecorded` event that provides the human readable failure string. Bonus points if there is a markdown version of the string, as many tools can render markdown directly.

**Comment by grynspan** [comment]
As of right now, the experimental event stream just encodes the fields of the events themselves. In order to make a stable API/ABI, we likely need to change that to a formal JSON schema with dedicated and intentional content, not just "whatever `JSONEncoder` produced."
