### ISSUE TITLE
#expect is causing mismatch behavior on Linux + release configuration build

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-testing#398]
### Description

I notice some test case is failing on Linux platform + release configuration.

> Test case pass on Linux+Debug & Darwin+Debug & Darwin+Release

## Issue 1: `#expect` issue

Digging into it, I found if I comment all `#expect` code or change to the old `XCTAssertTrue` from `XCTest`, the test case will pass normally.

## Issue 2: `withKnownIssue` issue

Also I can't record the such known issue with `withKnownIssue`. If I use it the failing case will magically pass again.

```swift
// A simplified version of the business code
struct PointerOffsetTests {
    @Test
    func demo() {
        var tuple = Tuple(first: 1, second: 2)
        typealias Base = Tuple<Int, Int>
        let firstOffset = PointerOffset<Base, Int>(byteOffset: 0)
        let secondOffset = PointerOffset<Base, Int>(byteOffset: 8)
        withUnsafePointer(to: tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 1)
            #expect(pointer[offset: secondOffset] == 2)
        }
        withUnsafeMutablePointer(to: &tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 1)
            #expect(pointer[offset: secondOffset] == 2)

            pointer[offset: firstOffset] = 3
            pointer[offset: secondOffset] = 4
                
            #expect(pointer[offset: firstOffset] == 3)
            #expect(pointer[offset: secondOffset] == 4)
        }
        withUnsafePointer(to: &tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 3)
            #expect(pointer[offset: secondOffset] == 4)
        }
        #if !canImport(Darwin) && !DEBUG
        // FIXME: The issue only occur on Linux + Release configuration (Swift 5.10)
        // Uncomment the following withKnownIssue code will make the result back to normal thus causing 5 new issues
//            withKnownIssue {
//                withUnsafePointer(to: tuple) { pointer in
//                    #expect(pointer[offset: firstOffset] == 3)
//                    #expect(pointer[offset: secondOffset] == 4)
//                }
//                #expect(tuple.first == 3)
//                #expect(tuple.second == 4)
//            }
        withUnsafePointer(to: tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 1)
            #expect(pointer[offset: secondOffset] == 2)
        }
        #expect(tuple.first == 1)
        #expect(tuple.second == 2)
        #else
        withUnsafePointer(to: tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 3)
            #expect(pointer[offset: secondOffset] == 4)
        }
        #expect(tuple.first == 3)
        #expect(tuple.second == 4)
        #endif
    }
}
```

### Expected behavior

Test case works normal

### Actual behavior

Test case is failing

### Steps to reproduce

Unzip the following DemoKit.zip on Ubuntu 22.04 + Swift 5.10 env.

Run `swift test -c release`

[DemoKit.zip](https://github.com/apple/swift-testing/files/15213513/DemoKit.zip)

### swift-testing version/commit hash

0.6.0

### Swift & OS version (output of `swift --version ; uname -a`)

Swift 5.10 release + Ubuntu 22.04 + Arm64

### Other info

My opinion is that the root cause of this issue is most likely not within swift-testing. It is rather caused by some optimization in the swift compiler, but the direct cause currently seems to be related to swift-testing.

Also reproducible with the following matrix

- swift-testing 0.6 / 0.8
- Swift 5.10

**Comment by Kyle-Ye** [comment]
I'm trying to upgrade to 0.8.0 to see if the issue still exists.

**Comment by Kyle-Ye** [comment]
> From @grynspan's reply on Slack channel
> I see you're hard-coding the pointer offsets to 0 and 8. In Swift, there's no guarantee of the layout of a type in memory and the compiler in release mode is free to aggressively rearrange bits for any reason. At a guess, you're stomping on the stack here.
Have you tried using [pointer(to:)](https://developer.apple.com/documentation/swift/unsafepointer/pointer(to:)) to compute inner pointers instead?

1. The hard-coding 0 and 8 is just for testing here. We can replace them with runtime calculated value here. And I do not think it is the issue here.

```swift
let firstOffset = PointerOffset<Base, Int>.offset { .of(&$0.first) }
let secondOffset = PointerOffset<Base, Int>.offset { .of(&$0.second) }
``` 

The `PointerOffset.offset` and `PointerOffset.of` implementation is using runtime offset here.

2. If you suspect the pointer issue, then let's consider the following code below.

I'm not using any pointer operation after "MARK". But adding `withKnownIssue` will magically cause mismatch behavior within the scope and after the scope.

```swift
struct PointerOffsetTests {
    @Test
    func demo() {
        var tuple = Tuple(first: 1, second: 2)
        typealias Base = Tuple<Int, Int>
        let firstOffset = PointerOffset<Base, Int>.offset { .of(&$0.first) }
        let secondOffset = PointerOffset<Base, Int>.offset { .of(&$0.second) }
        withUnsafePointer(to: tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 1)
            #expect(pointer[offset: secondOffset] == 2)
        }
        withUnsafeMutablePointer(to: &tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 1)
            #expect(pointer[offset: secondOffset] == 2)

            pointer[offset: firstOffset] = 3
            pointer[offset: secondOffset] = 4
                
            #expect(pointer[offset: firstOffset] == 3)
            #expect(pointer[offset: secondOffset] == 4)
        }
        withUnsafePointer(to: &tuple) { pointer in
            #expect(pointer[offset: firstOffset] == 3)
            #expect(pointer[offset: secondOffset] == 4)
        }
        // MARK
        print(tuple) // Tuple<Int, Int>(first: 1, second: 2)
        withKnownIssue {
            print(tuple) // Tuple<Int, Int>(first: 3, second: 4)
        }
        print(tuple) // Tuple<Int, Int>(first: 3, second: 4)
   }
}
```

**Comment by grynspan** [comment]
> The hard-coding 0 and 8 is just for testing here.

Then it's a variable we need to eliminate in order to narrow down the root cause of the issue.

Looking at the code you shared in the zip file:

```swift
    public static func of(_ member: inout Member) -> PointerOffset {
        withUnsafePointer(to: &member) { memberPointer in
            let offset = UnsafeRawPointer(memberPointer) - UnsafeRawPointer(invalidScenePointer())
            return PointerOffset(byteOffset: offset)
        }
    }    
```

This code is invalid. `memberPointer` is a _temporary_ pointer to a _copy_ of `member`, and `member` itself is a temporary copy of the value outside the call to `of(_:)`. The address you have here is almost certainly an arbitrary location on the stack that is unrelated to the original value (presumably `tuple`.) Mathing with it and `invalidScenePointer()` is going to give you an arbitrary value as your offset that has no relation to the address of `tuple`. Under different optimization regimes (release vs. debug) it's entirely unsurprising that you'd get different results.

As I suggested earlier, use [`UnsafePointer.pointer(to:)`](https://developer.apple.com/documentation/swift/unsafepointer/pointer(to:)) to get an inner pointer inside an existing value. Be aware that `withUnsafePointer(to:_:)` gives you a pointer to a _copy_ of the original value, not the address of the original value: in Swift, most values are not guaranteed to have unique addresses and the compiler must synthesize one when needed. So the pointer returned from `pointer(to:)` is only valid for the lifetime of the enclosing call to `withUnsafePointer(to:_:)`.

**Comment by Kyle-Ye** [comment]
Change to use [`pointer(to:)`](https://developer.apple.com/documentation/swift/unsafepointer/pointer(to:)) do seem to solve the issue. Thanks.

<img width="1501" alt="image" src="https://github.com/apple/swift-testing/assets/43724855/dfabc29a-4b08-4557-9e89-f4ec31c89f0d">

<img width="1489" alt="image" src="https://github.com/apple/swift-testing/assets/43724855/ecd4286e-3b73-458f-a691-a29d3455bdc8">

<img width="1499" alt="image" src="https://github.com/apple/swift-testing/assets/43724855/04797511-dfdf-4d19-9451-1edb5a0703c8">
