### ISSUE TITLE
Is it possible to run specific test cases in Xcode?

### ISSUE THREAD

**Issue by tareksabry1337** [apple/swift-testing#438]
### Description

We are migrating away from XCTestCase in an iOS Application and I'm wondering if it's possible to run specific test struct only on even method in side one of the test structs to avoid running all the tests all the time.

### Expected behavior

To be able to run specific test cases / entire test suite without needing to run everything.

### Actual behavior

We have one function only called testAll that runs everything

### Steps to reproduce

* Integrate swift-testing in an iOS App
* Add tests

### swift-testing version/commit hash

0.7.0

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
Darwin Tareks-Work-Machine.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

**Comment by grynspan** [comment]
That would require changes to Xcode, which is not part of the Swift open source project. If you're interested in new Xcode features, please use Apple's Feedback Assistant to request them.
