### ISSUE TITLE
Update About field the in GitHub

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-testing#460]
## Expected behavior

Add a Description and Website link in GitHub's about field

eg. 

- https://github.com/apple/swift-markdown

<img width="324" alt="image" src="https://github.com/apple/swift-testing/assets/43724855/fcc626d4-1e59-47b7-b9f2-cb17ad931e4e">

- https://github.com/apple/swift-docc-plugin

<img width="332" alt="image" src="https://github.com/apple/swift-testing/assets/43724855/ff26ebf8-29eb-46a7-97c9-b27985b5b070">

## Suggested change

```
Description:
swift-testing is a modern, open-source testing library for Swift with powerful and expressive capabilities.

Website:
https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing
```

## Current behavior

Empty about field. And people have to scroll to the bottom to find out the documentation page.

**Comment by Kyle-Ye** [comment]
The change can't be made by PR because the metadata is on GitHub not the repository.

It can only be changed by the someone who has edit permission of the repo.

**Comment by stmontgomery** [comment]
Thank you for pointing this out! I have added a description to the repository. We've decided to hold off on including a URL for now, but may revisit this later.

**Comment by Kyle-Ye** [comment]
> We've decided to hold off on including a URL for now, but may revisit this later.

I guess you may host swift-testing's official documentation elsewhere when it reaches 1.0 release and is landing into the toolchain release.(eg. apple.github.io / developer.apple.com or continue to use SwiftPackageIndex)

But since we still use SPI in README currently. I see no harm adding this link to GitHub about field.
