### ISSUE TITLE
Allow direct creation of Issues

### ISSUE THREAD

**Issue by younata** [apple/swift-testing#474]
### Description

Xcode's XCTest has the XCTIssue API for reporting issues, but the closest thing to creating and reporting an XCTIssue is `Issue.record`. Which has limitations and prevents me from providing semantics for why an expectation failed.

This limits the ability of [Nimble](https://github.com/Quick/nimble) to integrate with Swift Testing.

**Comment by grynspan** [comment]
Discussed in a lab.

We've so far resisted doing this in the general case because we want to steer developers toward specific API like `#expect()`. @younata's use case is integration with tools however, which requires a different set of interfaces from what we provide for test authors.

We currently offer a number of interfaces guarded by `@_spi(ForToolsIntegrationOnly)`. These interfaces are available when building Swift Testing from a package. However, SPI is not available when using the copy of Swift Testing included in Xcode 16.

Would it be useful if we added an `Issue.init` member guarded by `@_spi` in this way? Would that be sufficient for your needs?

**Comment by younata** [comment]
Hi @grynspan! Thanks for the quick response!

My concern with using `@_spi` (which I am unfamiliar with) is if this will affect Nimble's Cocoapods & Carthage integrations. For the Swift Packages integration, `@_spi` will work fine. But, naively, I'm planning to try to get Nimble's Cocoapods & Carthage integrations to use the built-in Swift Testing. Last I checked (and google isn't helping me here).
This is because there isn't a way for me to tell Cocoapods that I have a dependency on something that's only available as a swift package. I know for a fact that if I were to embed Swift Testing as a Package for the Carthage integration, then the tests will refuse to build unless you also add the Swift Testing package as a dependency to your app (which I know because [Nimble's Carthage integration is currently broken for the same reason](https://github.com/Quick/Quick/issues/1275)).

Blocking the integration on tools-only `@_spi` looks promising, but I have reservations about if it will work with the other package manager Nimble purports to support.

**Comment by stmontgomery** [comment]
I think we do need to expose the ability to programmatically initialize and record an `Issue` and have that eventually become regular API. I can take this. I can't currently commit to any particular timeframe for delivering this functionality, however.

If anyone would like to get started drafting an API proposal (using our [template](https://github.com/apple/swift-testing/blob/main/Documentation/Proposals/0000-proposal-template.md)) for this, that would certainly be welcome!

**Comment by stmontgomery** [comment]
Tracked internally as rdar://114106842

**Comment by younata** [comment]
> I can't currently commit to any particular timeframe for delivering this functionality, however.

My only timeline is that I'd like to be able to ship Swift Testing integration in Nimble when Xcode 16 is fully released.

> If anyone would like to get started drafting an API proposal (using our [template](https://github.com/apple/swift-testing/blob/main/Documentation/Proposals/0000-proposal-template.md)) for this, that would certainly be welcome!

I'm happy to take on that API proposal. It'll probably go through a few revisions before it's merged, though.

**Comment by younata** [comment]
Let's go with #490, as described in https://github.com/apple/swift-testing/pull/481#issuecomment-2218006284

**Comment by mbrandonw** [comment]
> We currently offer a number of interfaces guarded by `@_spi(ForToolsIntegrationOnly)`. These interfaces are available when building Swift Testing from a package. However, SPI is not available when using the copy of Swift Testing included in Xcode 16.

Hi @grynspan, sorry to comment on a closed issue, but it seems that `@_spi import` is working just fine for the Testing framework in Xcode. Is this officially supported to get access to the integration tools?

**Comment by grynspan** [comment]
@mbrandonw No, it's a bug in Xcode. Apple is investigating.

**Comment by mbrandonw** [comment]
Hi @grynspan, thanks! And good to know. Is there any update on the status of `CustomExecutionTrait`, and whether or not it will make it to the first official Xcode release of swift-testing?

**Comment by grynspan** [comment]
This is not the appropriate place for questions about Swift Testing in general. Please consider starting a thread on the Swift forums. Thanks!
