### ISSUE TITLE
#expect does not catch error

### ISSUE THREAD

**Issue by swhitty** [apple/swift-testing#504]
### Description

My assumption is that `#expect` would catch any errors thrown within, reporting failure.  It currently throws halting the test, preventing any further expectations.

[vision/swift-testing.md#expectations](https://github.com/swiftlang/swift-evolution/blob/main/visions/swift-testing.md#expectations) states:
> The most important details relevant to expectation failures are the values being compared or checked and the kind of expectation being performed (e.g. equal, not-equal, less-than, is-not-nil, etc.). Also, if any error was caught while evaluating an expression passed to an expectation, that should be included.

FB13882255

### Expected behavior

Behaviour similar to [XCTAssert](https://developer.apple.com/documentation/xctest/1500669-xctassert) where the  expression is an `@autoclosure` allowing errors to be caught and the failure reported.

I would expect the following to compile but the test to fail with something like `Expectation failed: try condition() threw Error`

```swift
@Test func testFoo() {
    let condition: () throws -> Bool = { throw CancellationError() }
    #expect(try condition())
}
```

### Actual behavior

Fails to compile with `❌ Errors thrown from here are not handled`

Adding `throws` to the test allows it to compile, but only the first `#expect` expression is run:

```swift
@Test func testFoo() throws {
    let condition: () throws -> Bool = { throw CancellationError() }
    let nextCondition: () throws -> Bool = { true }

    #expect(try condition())
    #expect(try nextCondition()) // never run!
}
```

### Steps to reproduce

Compile and run this test, the first expectation should fail, while the 2nd should pass.

```swift
@Test func testFoo() {
    let condition: () throws -> Bool = { throw CancellationError() }
    #expect(try condition())
    #expect(true)
}
```

### swift-testing version/commit hash

Xcode 16 Beta 2 (16A5171r)

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64

**Comment by grynspan** [comment]
It is intentional that errors are not caught by `#expect()`, and this is an intentional difference in behaviour from `XCTAssert()`. Our experience has shown that developers often find it confusing that this expression:

```swift
f(try g())
```

Behaves fundamentally differently from:

```swift
XCTAssertTrue(try g())
```

If you want execution of the test to continue if an error is thrown, consider wrapping the call in `#expect(throws:)`:

```
#expect(throws: Never.self) {
  #expect(try g())
}
```
