### ISSUE TITLE
Provide a JSON API to *just* list tests (via the callback, not stdout)

### ISSUE THREAD

**Issue by allevato** [apple/swift-testing#506]
### Description

If the JSON ABI entry point is used with `listTests: true` in its configuration, then the framework prints the list of all tests to stdout and then continues on executing tests ([implementation](https://github.com/apple/swift-testing/blob/2cdfccf6e891ef181be3091fc81670c3b6dd641c/Sources/Testing/EntryPoints/EntryPoint.swift#L35-L42)).

However, a client of the JSON entry point may want to query which tests are available without running anything yet. I think this can be hacked up today by passing in a filter regex that could not possibly match any test ID; then, the framework would terminate after running nothing. (Disclaimer: I haven't actually tried this.) However, doing so would still require the calling process to redirect stdout temporarily and then parse the output line-by-line.

Would it be possible for the JSON entry point to provide a mode where `listTests: true` (or something like it with a different name, if we need to preserve the current behavior) would report the list of tests back to the caller via the callback as a JSON payload instead, returning immediately without running anything?

### swift-testing version/commit hash

main

**Comment by grynspan** [comment]
> and then continues on executing tests (implementation).

It exits early, actually.

We have not defined a stable JSON interface for _input_ yet. If and when we do, it will likely include some sort of "list only" flag that produces a sequence of test records but does not run them.

**Comment by allevato** [comment]
> It exits early, actually.

Thanks! You're right—I misread the following `else` and didn't realize it was surrounding the entirety of the remaining logic.

> it will likely include some sort of "list only" flag that produces a sequence of test records but does not run them.

That sounds good to me! I should be able to work with the existing behavior until then.

**Comment by grynspan** [comment]
Actually, I'm going to reopen this and use it to track an experimental implementation of the described functionality, assuming it won't break VS Code. @plemarquand are you passing any additional arguments when you call `swift test list`?

**Comment by stmontgomery** [comment]
Tracked internally with rdar://130627856

**Comment by plemarquand** [comment]
@grynspan We [call it](https://github.com/swiftlang/vscode-swift/blob/d7f92c64dc20edbf6969e1ffe82c1fa720ad624c/src/TestExplorer/TestExplorer.ts#L255) with `—skip-build`, but otherwise no.
