### ISSUE TITLE
confirmation API without async calls

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift-testing#510]
### Description

I'm a beginner! I was trying to migrate over some XCTest-based code, and got tripped up by how `confirmation` works.

```swift
@Test func fails() async {
    // ERROR: Confirmation was confirmed 0 times, but expected to be confirmed 1 time
    await confirmation() { completion in
        _ = Task {
            completion()
        }
    }
}

@Test func succeeds() async {
    await confirmation() { completion in
        await Task {
            completion()
        }.value
    }
}
```

I get it, and it makes sense. It's just different from how `XCTests`'s `fulfillment` API works.

### Expected behavior

I wonder if it would be possible to maybe make an non-async overload that waits for the expected number of confirmations?

### Swift & OS version (output of `swift --version ; uname -a`)

```
swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx14.0
Darwin Matthews-MBP-2.localdomain 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

**Comment by grynspan** [comment]
If the code you're testing is not asynchronous, you can generally structure your code so you don't need a confirmation at all. However, if you do want to use one, you can just make your test function `async`. The actual body of the test isn't required to act asynchronously if it doesn't need to.

**Comment by grynspan** [comment]
It is intentional that the function does not block the caller waiting for work to complete. Such work is generally best handled using Swift concurrency instead. Watch [Go further with Swift Testing](https://developer.apple.com/wwdc24/10195) where we talk about this sort of pattern.

**Comment by grynspan** [comment]
In the video, we discuss this exact pattern. 🙂

**Comment by grynspan** [comment]
Yes, but in a _loving_ tone.

**Comment by grynspan** [comment]
Yes, but only out of love. 🙃
