### ISSUE TITLE
Creating Tests Programmatically

### ISSUE THREAD

**Issue by xlc** [apple/swift-testing#518]
### Description

I would like to define test cases in some fixtures file and then I can to read such file and programmatically generate test cases and run them.

Right now I need to either manually specify the test cases or discover and run all of them in a single test case, which isn't ideal.

**Comment by stmontgomery** [comment]
Hi @xlc, have you seen our documentation article [Implementing parameterized tests](https://swiftpackageindex.com/apple/swift-testing/0.10.0/documentation/testing/parameterizedtesting)? Or if you have tried this feature, can you elaborate on why you find it insufficient?

**Comment by xlc** [comment]
Let me give an example. I have a JSON file that defines the tests. 

```json
[
  { "name": "1+1", "input": [1, 1, "plus"], "output": 2 },
  { "name": "1+2", "input": [1, 2, "plus"], "output": 3 },
  { "name": "2*2", "input": [2, 2, ",multiply"], "output": 4 }
]
```

I would like to see 3 tests defined, and if any of it failed, the error will be attached to the corresponding test name. And all without me enumerate the test names in a Swift file
