### ISSUE TITLE
Trying to add swift testing package into our own package which has minimum deployment target iOS13.

### ISSUE THREAD

**Issue by MuhammadAhmedBaig** [apple/swift-testing#544]
### Description

While trying to add package it throws this error
package 'swift-testing' @ db6e08e9911f7e150948db347ebd08c2fdaa43f9 is using Swift tools version 6.0.0 but the installed version is 5.10.0 in https://github.com/apple/swift-testing.git

**Comment by grynspan** [comment]
Swift Testing requires Swift 6.
