### ISSUE TITLE
Observe state changes of PassThroughSubjects which is published inside a Task block.

### ISSUE THREAD

**Issue by MuhammadAhmedBaig** [apple/swift-testing#558]
I am trying to write test cases for my ViewModel, In my ViewModel I am doing the following:

**My Code:**
- Calling an API, and getting some data from the server (providing mock JSON for test cases).
- After the result, I assigned some value via ViewModel to one of the references existing in that ViewModel and also published changes via Subject (PassThroughSubject).

**Required Test:**
- In my test, I want to subscribe my publisher and wait for the expectation to be completed and then I will verify the values and compare those values to check either test is passed or not.

**Problem:**
I tried to perform test for **getAppConfigurationSettings** function but as this function already contained a Task so I tried to wait for the task value with **await task.value**, now the problems I am facing are:

- Task value returns only when **try await** passes to the next statement or completes its operation in **getAppConfigurationSettings**, so still my values are not updated, in XCTest we can add expectation waiting time and fulfill any alternate?
- How can I subscribe **stateSubject** and check if I receive the correct state?

`
    
    var stateSubject = PassthroughSubject<State, Never>()
    func getAppConfigurationSettings(isFetchAfterOtp: Bool = false) {
        Task {
            do {
                stateSubject.send(.loading)
                let response = try await self.httpClient.asyncRequest(endpoint: LaunchingEndPoint.getConfigurations, responseModel: AppHomeSettingsResponseModel.self)
                if response.status ?? false {
                    self.configureAppSettings(model: response.result)
                }
                if !isFetchAfterOtp {
                    self.stateSubject.send(.successWithSettings)
                }
            }  catch let error as ApiResponse {
                handleApiError(error)
            }
        }
    }`

I tried to write test like this.
`

    var viewModel: LaunchingViewModelProtocol = LaunchingViewModel(httpClient: MockHttpClient(),
                                                                   userContext: UserContext.getInstance())
    @Test func getAppConfig() async throws {
        let task = Task {
            viewModel.getAppConfigurationSettings(isFetchAfterOtp: false)
        }
        await task.value
        // SUBSCRIPTION FOR STATE CHANGES
    }
`

**Comment by grynspan** [comment]
Looks like you're using Combine, right? This is maybe a question more suited for the Swift or Apple Developer forums as it has to do with using the Combine framework, not so much to do with Swift Testing. I suggest starting a thread on the forums! 🙂

**Comment by MuhammadAhmedBaig** [comment]
Hey @grynspan, 

I hope you are doing well.

Thanks for the reply, I think you got me wrong here, What my point is in XCTest we can add Expectations which has a wait function as well, I want to use a similar functionality with Swift Testing, is it possible? also I am also pasting the code of XCTest maybe it will help to understand the question.

`
class LaunchVMTestCase: XCTestCase {
    var viewModel: LaunchingViewModelProtocol = LaunchingViewModel(httpClient: MockHttpClient(),
                                                                   userContext: UserContext.getInstance())
    
    var cancellable = Set<AnyCancellable>()
    
    func testGetAppConfig() async {
        let expectation = expectation(description: "wait for the changes in subject")
        self.viewModel.stateSubject.sink { state in
            if state != .loading {
                expectation.fulfill()
                XCTAssertTrue(state == .successWithSettings)
            }
        }.store(in: &self.cancellable)
        
        let task = Task {
            viewModel.getAppConfigurationSettings(isFetchAfterOtp: false)
        }
        await fulfillment(of: [expectation])
    }
}`


In **testGetAppConfig** function we have **expectation** and at the end of the function we are waiting for **fulfillment** of that expectation, how can we convert this to the new swift testing framework, do we have any replacement for **expectation** and **fulfillment**?

**Comment by grynspan** [comment]
We discuss similar patterns in [Go further with Swift Testing](https://developer.apple.com/wwdc24/10195). This particular pattern is often better-modelled as a Swift continuation rather than as a blocking call to `wait(for:)` or `fulfillment(of:)`.
