### ISSUE TITLE
Improve assertion that a function throws a specific error using typed throws and type inference

### ISSUE THREAD

**Issue by ZevEisenberg** [apple/swift-testing#571]
### Description

There is currently a [function to test throwing a specific error](https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing/expect(throws:_:sourcelocation:performing:)-1xr34), but it requires you to fully specify the type name. With typed throws, we could use type inference to reduce boilerplate.

Note: would likely require fixing https://github.com/swiftlang/swift/issues/75430 first.

### Expected behavior

This should be possible

```swift
#expect(throws: .batteryDied) {
  FoodTruck.shared.engine.batteryLevel = 0
  try FoodTruck.shared.engine.start()
}
```

### Actual behavior

You have to fully specify the error value:

```swift
#expect(throws: EngineFailureError.batteryDied) {
  FoodTruck.shared.engine.batteryLevel = 0
  try FoodTruck.shared.engine.start()
}
```

**Comment by grynspan** [comment]
It is intentional that this macro and its implementation do not use typed throws. When an error is thrown via the typed throws mechanism, the source location of the `throw` is lost due to how typed throws is implemented in the Swift runtime.

**Comment by ZevEisenberg** [comment]
Please forgive my ignorance - I haven't had a chance to dig in to the details of swift-testing. Why would we need the source location the `throw`? I figure it should work similarly to the existing function. The macro shouldn't need to support type inference, since that would be resolved in the expanded code? I'm guessing there's something I'm missing about which information is needed in which part of the macro/call-site dance, but assuming the above [bug that I mentioned above](https://github.com/swiftlang/swift/issues/75430) were fixed, an implementation vaguely along these lines would work, no?

```swift
// Many details elided; this is just a sketch
func assertThrowsGeneric<Failure: Error & Equatable>(
  _ expression: @autoclosure () throws(Failure) -> some Any,
  _ expectedError: @autoclosure () -> Failure
) {
  do {
    _ = try expression()
  } catch {
    assert(error == expectedError())
  }
}
```

**Comment by grynspan** [comment]
Xcode shows the backtrace of the error on throw for diagnostic purposes (as it does with XCTest.)

Macros need to be syntactically valid before expansion, and unfortunately `#expect(throws: .foo) { ... }` is not, at least as far as the compiler is concerned today, and at least according to my quick at-desk experiment.

**Comment by ZevEisenberg** [comment]
Would they be valid if my linked issue were fixed? It seems there's a problem with type inference for typed throws as generics.

**Comment by grynspan** [comment]
I don't know if the issue you linked would be sufficient to resolve the problem with type resolution on the macro side, but even if it were, we intentionally don't use typed throws in Swift Testing due to the loss of associated metadata.

**Comment by ZevEisenberg** [comment]
I think we may be talking past each other. I see the `Result<Void, any Error>` used to carry the `ExpectationFailedError` through the internals of the expectation checking code. But that's (I think) separate from the functions that are being tested, which are currently `performing expression: () async throws -> R`, and I'm suggesting modifying them or adding new ones like `performing expression: () async throws(E) -> R`.

I couldn't get this to compile, but I'm not familiar with the various layers involved. Here's an example of an error I was getting:
<img width="972" alt="image" src="https://github.com/user-attachments/assets/dacb6a3a-9995-4605-bb0c-ac18914103d5">
Perhaps that does mean the `Result<Void, any Error>` is implicated? I'm not sure. Here's a super rough patch of my attempt. Macros are confusing 😅 (And I'm also not sure if the `FullTypedThrows` feature flag has to be enabled, per [this thread](https://forums.swift.org/t/closure-property-that-throws-typed-error-in-swift-6-result-in-compiling-error/72433).)

**Comment by grynspan** [comment]
I completely understand where you're coming from and why typed throws is appealing here, but even putting aside _just getting the darned thing to compile dagnabbit_, typed throws breaks Xcode's ability to track the call stack that produced a thrown error, so we don't want to use it here; it would degrade the overall Xcode experience. :(

**Comment by ZevEisenberg** [comment]
> typed throws breaks Xcode's ability to track the call stack that produced a thrown error

And that's because it's wrapping the thrown error in an error that captures the context about where it was thrown, right? I don't suppose there's any chance of adding a generic initializer to that wrapper error, or even an erasing initializer? It could still be untyped under the hood, and the assertion mechanism would handle casting and checking just like the untyped version does? Sorry this is all very general; I couldn't quite sink my teeth into the code enough to see precisely where the problem lies.

**Comment by grynspan** [comment]
The Swift runtime includes a special hook, `swift_willThrow`, that is set by Swift Testing and XCTest. When it's called, Swift Testing attaches a stack trace to the existential box containing the thrown error. Typed throws doesn't use existential boxes, so this trick doesn't work.

**Comment by ZevEisenberg** [comment]
💡 I see! Thank you for taking the time to explain ❤️
