### ISSUE TITLE
Remove "Unconditionally" from `Issue.record` messaging

### ISSUE THREAD

**Issue by stephencelis** [apple/swift-testing#574]
### Description

While a more official API for extending `Issue.record` with more issue kinds is being fleshed out, it might also be worth removing the "Unconditionally" from the standard output. `Issue.record` is still an API that is convenient to reach for to write test helpers, but when a test helper _should_ fail given a condition, the "unconditionally" part of the messaging can be confusing. "Failed" is probably enough to communicate when an issue is recorded.

### Expected behavior

`Issue.record` ideally emits a basic "Failed" message, like XCTest does.

### Actual behavior

`Issue.record` emits "Unconditionally failed" instead.

### Steps to reproduce

Invoke `Issue.record`.

### swift-testing version/commit hash

Xcode 16 beta 4

### Swift & OS version (output of `swift --version && uname -a`)

N/A

**Comment by grynspan** [comment]
The word "unconditionally" here is a lie, because while the failure is unconditional because somebody called `Issue.record()`, it's not necessarily true that the surrounding code is unconditionally executing.
